In [1]:
import pandas as pd
import os
from bs4 import BeautifulSoup
import re
import glob
import random
from tqdm import tqdm
import json

# disable chained assignment warning
pd.options.mode.chained_assignment = None

tqdm.pandas()

In [2]:
# go to data/htmls/ for each folder make a list of 100 random htmls and store them as a zip file in the root folder
import os
import random
import zipfile

# Path: hrefs_analysis.ipynb
DATA_DIR = 'data/'
HTML_DIR = 'data/htmls/'

# get the list of folders
folders = os.listdir(HTML_DIR)
folders

['rionegro',
 'clarin',
 'c5n',
 'lanacion',
 'infobae',
 'pagina12',
 'lavoz',
 'eldestapeweb',
 'perfil']

### Make a zipfile of 100 random htmls for each new-web to obeserve for writing a scrapper.

In [3]:
# # for each folder make a list of 100 random htmls and store them as a zip file in the root folder
# for folder in folders:
#     # get the list of htmls
#     htmls = os.listdir(HTML_DIR+folder)
#     # get 100 random htmls
#     random_htmls = random.sample(htmls, 100)
#     # make a zip file
#     zip_file = zipfile.ZipFile(DATA_DIR+folder+'.zip', 'w')
#     for html in random_htmls:
#         zip_file.write(HTML_DIR+folder+'/'+html, html)
#     zip_file.close()

### Define a scrape function for each website

In [4]:
# # choose 100 random htmls from c5n
# # get the list of htmls

# # glob 100 random htmls from data/htmls/*/
# html_folders = os.listdir('data/htmls/')
# html_dict = {}
# for folder in html_folders:
#     html_dict[folder] = random.sample(glob.glob(f'data/htmls/{folder}/*.html'), 10)


# scraping_dict = {
#                   # tag, attributes, classifier
#     'c5n' : {
#         'title': ['h1', {'class': 'news-headline__title'}],
#         'date': ['time', {'itemprop': 'datePublished'}, 'text'],
#         'text': [True, {'class': re.compile('article-body article-body')}]
#     },

#     'clarin':
#     {
#         'title': ['h1', {'class': 'storyTitle'}],
#         'date': ['meta', {'itemprop': 'datePublished'}, 'content'],
#         'text': ['div', {'class': 'StoryTextContainer'}]
#     },

#     'eldestapeweb':{
#         'title': ['h1', {'class': 'titulo'}],
#         'date': ['div', {'class': 'fecha'}, 'text'],
#         'text': ['div', {'itemprop': 'articleBody'}]
#     },

#     'lanacion':{
#         'title': ['h1', {'class': re.compile('com-title')}],
#         'date': ['span', {'class': 'mod-date'}, 'text'],
#         'text': [True, {'class': re.compile('com-paragraph')}]
#     },
    
#     'lavoz':{
#         'title': ['h1', {'class': re.compile('false h1 boldbold')}],
#         'date': ['div', {'class': re.compile('story-meta-datetime')}, 'text'],
#         'text': ['div', {'class': re.compile('story-content')}]

#     },

#     'perfil':{
#         'title': ['h1', {'class': 'article__title'}],
#         'date': ['time', {'class': 'article__date'}, 'text'],
#         'text': ['div', {'class': re.compile('article__content')}]
#     },
    
#     'pagina12':{
#         'title': ['h1', {}],
#         'date': ['time', {}, 'text'],
#         'text': ['div', {'class': re.compile('article-main-content article-text')}]

#     },
    
#     'infobae' :{
#         'title': ['h1', {'class': re.compile('article-headline')} ],
#         'date': ['span', {'class': 'sharebar-article-date'}, 'text'],
#         'text': ['div', {'class': re.compile('body-article')}]
#     },

#     'rionegro':{
#         'title': ['h1', {'class': 'newsfull__title'}],
#         'date': ['time', {'class': 'newsfull__time'}, 'text'],
#         'text': ['div', {'class': 'newsfull__body'}]
#     },

# }

# # # c5n scrapper
# for html in html_dict['infobae']:

#     try:
#         print(html)
#         # read the html
#         with open(html, 'r') as f:
#             html_file = f.read()
#         # parse the html
#         soup = BeautifulSoup(html_file, 'html.parser')
#         website = html.split('/')[2]
#         print(website)
#         title_tag = scraping_dict[website]['title']
#         date_tag = scraping_dict[website]['date']
#         text_tag = scraping_dict[website]['text']
#         # get the title in h1 with class 'news-headline__title'
#         title = soup.find(name=title_tag[0], attrs=title_tag[1]).text
#         print(title)
#         # get the date in time with itemprop 'datePublished' stored in 'content' tag
#         date = soup.find(date_tag[0], date_tag[1])[date_tag[2]] if date_tag[2]!='text' else soup.find(date_tag[0], date_tag[1]).text
#         print(date)
#         # get the text of any class containing keywords: 'article-body article-body'
#         text_elements = soup.find_all(name=text_tag[0], attrs=text_tag[1])
#         print(len(text_elements))


#         text = ''
#         for text_element in text_elements:
#             # get all the <p> tags inside of text_element and their text if the current text_element is not a <p> tag
#             if text_element.name != 'p':
#                 p_tags = text_element.find_all('p')
#                 for p_tag in p_tags:
#                     text += '\n'+p_tag.text.strip()
#             else:
#                 text += '\n'+text_element.text.strip()
#         print('Date:', date)
#         print('Title:', title)
#         print('Text:', text)
#         print("-----------------------------------------")
#         print()
        
#     except Exception as e:
#         # print('Date:', date)
#         # print('Title:', title)
#         # print('Text:', text)
#         print('Error:', e) 
#         print("-----------------------------------------")

In [5]:
def rename_yt_csvs():
    # rename the csvs in the candidates_csvs folder.
    # the csvs are named as: 'candidato nombre apellido_dates.csv'
    # rename it to: 'candidato_nombre_apellido.csv'
    # get the list of csvs
    csvs = glob.glob('candidates_csvs/*.csv')

    for csv in csvs:
        # get the name of the csv
        csv_name = csv.split('/')[1]
        # get the name of the candidate
        candidate_name = csv_name.split('_2023')[0].lower().replace(' ', '_')
        # rename the csv
        os.rename(csv, 'candidates_csvs/'+candidate_name+'.csv')

### Making a dataframe from yt_transcripts and the scraped data

In [6]:
# reading the scraped data
df_scraped = pd.read_csv('data/htmls_scraped/scraped_data.csv')
df_scraped

csvs = glob.glob('candidates_csvs/*.csv')
df_candidates = pd.DataFrame()
for csv in csvs:
    # read the csv only 1,2 and 4th columns
    df_candidates = pd.concat([df_candidates, pd.read_csv(csv, usecols=[2,3,4], names=['vid_id', 'date', 'title'])])
    df_candidates = df_candidates.reset_index(drop=True)


transcripts_dict = {}
for json_file in glob.glob('data/transcripts/*.json'):
    candidate_name = json_file.split('/')[2].split('.json')[0]
    # read the json file
    with open(json_file, 'r') as f:
        json_data = json.load(f)
    for vid_id, transcript in json_data.items():
        transcripts_dict[vid_id] = transcript
df_transcripts = pd.DataFrame(list(transcripts_dict.items()), columns=['vid_id', 'text'])


# merge the transcripts with the df_candidates based on the vid_id
merged_df = pd.merge(df_candidates, df_transcripts, on='vid_id', how='left')  # or how='left', etc. as per requirement
merged_df = merged_df.dropna()

# drop vid_id column and a source column for which all the entries should be youtube
merged_df = merged_df.drop(['vid_id'], axis=1)
merged_df['source'] = 'youtube'
merged_df = merged_df.reset_index(drop=True)
merged_df

,date,title,text,source
0,2023-09-29T03:37:37Z,Lan√ßamento da BMW R1300GS ao vivo de Berlim,transcript_disabled,youtube
1,2023-09-29T02:14:21Z,BANDNEWS MANAUS 28.09.23,transcript_disabled,youtube
2,2023-09-29T00:08:26Z,ALERTA | AO VIVO | 28/09/2023,transcript_disabled,youtube
3,2023-09-28T23:08:20Z,Marcelo Ramal por Radio Locos por Bs As,Marcelo ramal es un ex legislador de la\nciuda...,youtube
4,2023-09-28T22:18:29Z,Jorge Altamira por Radio Horizonte de Bariloche,que Altamira estamos hablando de un\nreferente...,youtube
...,...,...,...,...
56873,2023-08-02T10:09:42Z,Trinchera (01/08/23): Entrevista a Cesar Biond...,transcript_disabled,youtube
56874,2023-08-02T02:45:23Z,NICOLAS MORAS-LOS LIBERALES (PARODIA),buenas noches amigos soy Nicol√°s moraz\nesta n...,youtube
56875,2023-08-01T21:00:12Z,"AGUSTINA KAMPFER entrevist√≥ a C√âSAR BIONDINI, ...",le voy a dar la bienvenida al pr√≥ximo\ninvitad...,youtube
56876,2023-07-31T21:00:09Z,Entrevista a C√âSAR BIONDINI en &quot;Somos PM&...,[M√∫sica]\nbueno y de Cara a las paso de dentro...,youtube
56877,2023-07-31T14:00:01Z,Elecciones 2023 | Cobertura especial de Canal ...,en agosto y de noticias y ganar nueve\nvan a s...,youtube

In [35]:
# rename 'website' coulumn to 'source'
df_scraped = df_scraped.rename(columns={'website': 'source'})

# append the df_scraped with the merged_df based on the title
df_test = pd.concat([df_scraped, merged_df], ignore_index=True)

df_test

,source,title,date,text
0,rionegro,Ya est√° casi todo listo para licitar la obra d...,15/12/2022 13:53 | Actualizado 15/12/2022 14:06,\nEl Ministerio de Obras P√∫blicas de Naci√≥n di...
1,rionegro,Elecciones en R√≠o Negro: Horne asegura que hub...,18/04/2023 18:23,\nLa excandidata a gobernadora Silvia Horne co...
2,rionegro,Desconcierto por el hallazgo del ¬´beb√©¬ª del mo...,04/01/2023 11:49 | Actualizado 04/01/2023 11:50,\nDescubrieron una ¬´extra√±a bestia¬ª varada en ...
3,rionegro,¬´Me di por vencida¬ª: por qu√© Marie Kondo ya no...,29/01/2023 10:36,"\nMarie Kondo, ¬´la reina del orden¬ª, admiti√≥ h..."
4,rionegro,Juan Manzur podr√≠a irse de la Jefatura de Gab...,23/01/2022 15:39 | Actualizado 23/01/2022 19:08,\nJuan Luis Manzur presentar√≠a en las pr√≥ximas...
...,...,...,...,...
386795,youtube,Trinchera (01/08/23): Entrevista a Cesar Biond...,2023-08-02T10:09:42Z,transcript_disabled
386796,youtube,NICOLAS MORAS-LOS LIBERALES (PARODIA),2023-08-02T02:45:23Z,buenas noches amigos soy Nicol√°s moraz\nesta n...
386797,youtube,"AGUSTINA KAMPFER entrevist√≥ a C√âSAR BIONDINI, ...",2023-08-01T21:00:12Z,le voy a dar la bienvenida al pr√≥ximo\ninvitad...
386798,youtube,Entrevista a C√âSAR BIONDINI en &quot;Somos PM&...,2023-07-31T21:00:09Z,[M√∫sica]\nbueno y de Cara a las paso de dentro...
386799,youtube,Elecciones 2023 | Cobertura especial de Canal ...,2023-07-31T14:00:01Z,en agosto y de noticias y ganar nueve\nvan a s...

In [39]:
# check if this title = 'Entre pases de factura internos, Jorge Macri define su vice buscando evitar el balotaje'  exists in the dataset
df_test.query('title=="Entre pases de factura internos, Jorge Macri define su vice buscando evitar el balotaje" & source=="clarin"')

,source,title,date,text
57566,clarin,Con Lisandro Mart√≠nez y Garnacho desde el arra...,2023-08-14T21:23:52Z,\nManchester United puso primera en la Premier...
57571,clarin,La poderosa hierba que ayuda a equilibrar el m...,2023-08-17T19:34:32Z,\nLas hierbas se convirtieron en un pilar clav...
57646,clarin,Qu√© revelan las iniciales de tu nombre sobre t...,2023-08-15T11:48:50Z,\nLa primera se√±al de identidad es nuestro nom...
57880,clarin,Quiniela de C√≥rdoba: resultado del sorteo de l...,2023-08-12T18:02:00Z,\nYa se conocen los n√∫meros ganadores del sort...
58046,clarin,Quiniela de la Provincia: resultado del sorteo...,2023-08-12T18:01:00Z,\nYa se conocen los n√∫meros ganadores del sort...
...,...,...,...,...
70227,clarin,Quiniela de la Provincia: resultado del sorteo...,2023-08-18T14:31:02Z,\nYa se conocen los n√∫meros ganadores del sort...
70293,clarin,FedEx St. Jude Championship: Emiliano Grillo l...,2023-08-12T19:00:27Z,"\nTras la tercera vuelta, Emiliano Grillo pudo..."
70320,clarin,Emma Thompson es una viuda que acude a un taxi...,2023-08-12T20:43:35Z,"\nEn 2022¬†vimos dos versiones muy, pero muy di..."
70324,clarin,"Arte en √©poca de crisis: vuelve BADA, la feria...",2023-08-14T20:26:41Z,\nCuando todo es incertidumbre y ansiedad pol√≠...
70391,clarin,Tsitsipas detect√≥ que una mujer imitaba el son...,2023-08-17T12:22:13Z,\nStefanos Tsitsipas derrot√≥ por 7-6(3) y 7-6(...

In [ ]:
#check if an

In [7]:
# rename 'website' coulumn to 'source'
df_scraped = df_scraped.rename(columns={'website': 'source'})

# append the df_scraped with the merged_df based on the title
df = pd.concat([df_scraped, merged_df], ignore_index=True)

df

,source,title,date,text
0,rionegro,Ya est√° casi todo listo para licitar la obra d...,15/12/2022 13:53 | Actualizado 15/12/2022 14:06,\nEl Ministerio de Obras P√∫blicas de Naci√≥n di...
1,rionegro,Elecciones en R√≠o Negro: Horne asegura que hub...,18/04/2023 18:23,\nLa excandidata a gobernadora Silvia Horne co...
2,rionegro,Desconcierto por el hallazgo del ¬´beb√©¬ª del mo...,04/01/2023 11:49 | Actualizado 04/01/2023 11:50,\nDescubrieron una ¬´extra√±a bestia¬ª varada en ...
3,rionegro,¬´Me di por vencida¬ª: por qu√© Marie Kondo ya no...,29/01/2023 10:36,"\nMarie Kondo, ¬´la reina del orden¬ª, admiti√≥ h..."
4,rionegro,Juan Manzur podr√≠a irse de la Jefatura de Gab...,23/01/2022 15:39 | Actualizado 23/01/2022 19:08,\nJuan Luis Manzur presentar√≠a en las pr√≥ximas...
...,...,...,...,...
386795,youtube,Trinchera (01/08/23): Entrevista a Cesar Biond...,2023-08-02T10:09:42Z,transcript_disabled
386796,youtube,NICOLAS MORAS-LOS LIBERALES (PARODIA),2023-08-02T02:45:23Z,buenas noches amigos soy Nicol√°s moraz\nesta n...
386797,youtube,"AGUSTINA KAMPFER entrevist√≥ a C√âSAR BIONDINI, ...",2023-08-01T21:00:12Z,le voy a dar la bienvenida al pr√≥ximo\ninvitad...
386798,youtube,Entrevista a C√âSAR BIONDINI en &quot;Somos PM&...,2023-07-31T21:00:09Z,[M√∫sica]\nbueno y de Cara a las paso de dentro...
386799,youtube,Elecciones 2023 | Cobertura especial de Canal ...,2023-07-31T14:00:01Z,en agosto y de noticias y ganar nueve\nvan a s...

In [8]:
# # show 10 entries for each website
# for website in df['source'].unique():
#     print(website)
#     display(df[df['source']==website].head(10))
#     print('---------------------------------------------')

In [9]:
# preprocess the text column
def preprocess_text(text):
    text = re.sub('\n+',' ',text)
    text = re.sub(' +',' ',text)
    text = re.sub('\t+',' ',text)
    text = re.sub('\r+',' ',text)
    text = text.lower()
    text = text.strip()
    return text


# Mapping of Spanish month names to English, include 3 letter words for month as well
month_mapping = {
    'enero': 'January',
    'febrero': 'February',
    'marzo': 'March',
    'abril': 'April',
    'mayo': 'May',
    'junio': 'June',
    'julio': 'July',
    'agosto': 'August',
    'septiembre': 'September',
    'octubre': 'October',
    'noviembre': 'November',
    'diciembre': 'December',
    'ene': 'January',
    'feb': 'February',
    'mar': 'March',
    'abr': 'April',
    'may': 'May',
    'jun': 'June',
    'jul': 'July',
    'ago': 'August',
    'sep': 'September',
    'oct': 'October',
    'nov': 'November',
    'dic': 'December'
}

# Mapping of Spanish day names to English in lower case letters
day_mapping = {
    'lunes': 'Monday',
    'martes': 'Tuesday',
    'mi√©rcoles': 'Wednesday',
    'jueves': 'Thursday',
    'viernes': 'Friday',
    's√°bado': 'Saturday',
    'domingo': 'Sunday'
}

# month to number mapping using three letter words
month_to_number = {
    'jan': '01',
    'feb': '02',
    'mar': '03',
    'apr': '04',
    'may': '05',
    'jun': '06',
    'jul': '07',
    'aug': '08',
    'sep': '09',
    'oct': '10',
    'nov': '11',
    'dec': '12'
}

def clean_dates(date):
    # remove newlines
    date = re.sub('\n', '', date)
    date = date.split('|')[0]
    date = date.split('T')[0]
    date = date.replace('Publicado: ', '')
    # remove a.m. and p.m.
    date = re.sub('a.m.|p.m.', '', date)
    # remove 'ES(T)'
    date = date.replace('ES', '')
    # remove the 24h time
    date = re.sub('\d{2}:\d{2}', '', date)
    # remove '-'
    date = date.replace(' - ', '')

    date = date.lower()
    # remove 'de' and commas
    date = date.replace('de', '')
    date = date.replace(',', '')
    # remove spanish days
    for day in day_mapping.keys():
        date = date.replace(day, '')
    # replace spanish months with English
    for month in month_mapping.keys():
        date = date.replace(month, month_mapping[month])
    
    date = date.lower()
    # remove extra spaces
    date = re.sub(' +', ' ', date)

    # convert 'year-month-day' pattern to this to day-month-year
    if re.search('\d{4}-\d{2}-\d{2}', date):
        date = date.split('-')
        date = date[2]+'-'+date[1]+'-'+date[0]

    date = date.strip()
    # convert day/month/year to day-month-year
    if re.search('\d{1,2}/\d{1,2}/\d{4}', date):
        date = date.split('/')
        date = date[0]+'-'+date[1]+'-'+date[2]
    
    date = date.lower()
    # # convert day Month(english) year to day-month-year
    if re.search('\d+ ([A-Za-z]+) \d+', date):
        split = date.split(' ')
        date = split[0]+'-'+month_to_number[split[1][:3]]+'-'+split[2]
    
    return date

In [10]:
df['date'] = df['date'].astype(str).apply(clean_dates)
# drop all the rows with null values
df = df.dropna()
# drop all the non-numerical values for new_dates
df = df[df['date'].progress_apply(lambda x: re.search('\d+-\d+-\d+', x)!=None)]
# convert to datetime
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 365396/365396 [00:00<00:00, 477111.37it/s]

In [11]:
# combine title and text columns
df['text'] = df['title'] + '. ' + df['text']
# drop the title column
df = df.drop(['title'], axis=1)
df['text'] = df['text'].progress_apply(preprocess_text)

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 365210/365210 [02:50<00:00, 2136.54it/s]

In [12]:
# show 10 entries for each website
for website in df['source'].unique():
    print(website)
    display(df[df['source']==website].head(5))
    print('---------------------------------------------')

rionegro

     source       date                                               text
0  rionegro 2022-12-15  ya est√° casi todo listo para licitar la obra d...
1  rionegro 2023-04-18  elecciones en r√≠o negro: horne asegura que hub...
2  rionegro 2023-01-04  desconcierto por el hallazgo del ¬´beb√©¬ª del mo...
3  rionegro 2023-01-29  ¬´me di por vencida¬ª: por qu√© marie kondo ya no...
4  rionegro 2022-01-23  juan manzur podr√≠a irse de la jefatura de gabi...

---------------------------------------------
clarin

       source       date                                               text
57415  clarin 2023-05-05  verstappen despej√≥ las dudas y domin√≥ en miami...
57416  clarin 2023-05-10  mendoza: encontraron sangre en la casa de ivan...
57417  clarin 2023-09-17  vandalizaron con pintura la puerta de brandebu...
57418  clarin 2023-09-29  t√© de romero y canela: para qu√© sirve, benefic...
57419  clarin 2023-06-12  el gobernador electo de san luis toma partido ...

---------------------------------------------
c5n

      source       date                                               text
70449    c5n 2023-08-14  plazos fijos: cu√°nto gano por depositar 96.000...
70450    c5n 2023-09-23  la excelente confiter√≠a de buenos aires que ha...
70451    c5n 2022-04-07  mick schumacher se emocion√≥ al recordar a su p...
70452    c5n 2023-09-07  la respuesta de lourdes s√°nchez tras los comen...
70453    c5n 2022-12-30  bono para empleadas dom√©sticas: se reintegrar√°...

---------------------------------------------
lanacion

          source       date                                               text
128239  lanacion 2023-06-19  china recorta tasas de referencia de pr√©stamos...
128240  lanacion 2021-12-31  coronavirus en argentina: casos en rauch, buen...
128241  lanacion 2023-06-17  los simpson, la familia de clase media baja de...
128242  lanacion 2022-08-17  el se√±or de los anillos: los anillos de poder ...
128243  lanacion 2022-06-29  gobierno de ecuador retoma di√°logo con ind√≠gen...

---------------------------------------------
infobae

         source       date                                               text
183340  infobae 2023-10-10  cr√≥nica del real madrid - dallas mavericks: 12...
183341  infobae 2023-10-03  el tremendo accidente de un trapecista chileno...
183342  infobae 2017-11-10  m√°s all√° de los abdominales: 12 alimentos esen...
183343  infobae 2020-05-26  las claves fit del entrenador de meghan markle...
183344  infobae 2020-09-08  por qu√© piden que livia brito sea expulsada de...

---------------------------------------------
pagina12

          source       date                                               text
188106  pagina12 2022-02-06  juan grabois desminti√≥ haber estado internado ...
188107  pagina12 2023-09-12  "el norte argentino necesita que sergio massa ...
188108  pagina12 2023-08-31  myriam bregman cruz√≥ a javier milei: "es todo ...
188109  pagina12 2023-09-27  ahora massa comienza su b√∫squeda del voto a vo...
188110  pagina12 2023-05-20  asoma juan grabois: "esto no es un simulacro. ...

---------------------------------------------
lavoz

       source       date                                               text
189387  lavoz 2023-09-04  juicio al falso m√©dico en r√≠o cuarto: re√±ida b...
189388  lavoz 2023-09-16  impactante video: un avi√≥n cay√≥ encima de un a...
189389  lavoz 2023-07-28  lana del rey caus√≥ sorpresa al ser vista traba...
189392  lavoz 2023-05-07  talleres gole√≥ a atlanta por el torneo de asce...
189394  lavoz 2023-05-20  empleadas dom√©sticas: cu√°nto deben cobrar por ...

---------------------------------------------
eldestapeweb

,source,date,text
228015,eldestapeweb,2022-07-12,salta fue considerada por la revista time como...
228016,eldestapeweb,2023-04-21,sale a subasta una pintura de picasso valuada ...
228017,eldestapeweb,2022-12-14,rusia descart√≥ la posibilidad de una tregua en...
228018,eldestapeweb,2023-09-23,"ante 50.000 personas y macron, francisco recor..."
228019,eldestapeweb,2023-07-08,karina la princesita se quebr√≥ y le hizo un de...

---------------------------------------------
perfil

        source       date                                               text
288015  perfil 2022-07-08  el kirchnerismo duro baj√≥ un cambio y puso pa√±...
288016  perfil 2022-10-07  c√≥mo saber si un neum√°tico es nuevo, usado o s...
288017  perfil 2022-12-30  tres renuncias en 24 horas: los motivos detr√°s...
288018  perfil 2022-12-15  reino unido en shock tras la muerte de 4 ni√±os...
288019  perfil 2022-05-01  d√≠a del trabajador: la "payasesca" interna k t...

---------------------------------------------
youtube

         source       date                                               text
329922  youtube 2023-09-29  lan√ßamento da bmw r1300gs ao vivo de berlim. t...
329923  youtube 2023-09-29      bandnews manaus 28.09.23. transcript_disabled
329924  youtube 2023-09-29  alerta | ao vivo | 28/09/2023. transcript_disa...
329925  youtube 2023-09-28  marcelo ramal por radio locos por bs as. marce...
329926  youtube 2023-09-28  jorge altamira por radio horizonte de bariloch...

---------------------------------------------

In [17]:
from unidecode import unidecode

candidates = {
    'Myriam Bregman' :    ['Myriam Bregman', 'Miriam Bregman', 'Miriam Breman', 'Myriam Breman', 'Myriam', 'Miriam',],
    'Gabriel Solano' :    ['Gabriel Solano', 'Solano',],
    'Alejandro Biondini' :    ['Alejandro Biondini', 'Biondini',],
    'Juan Schiaretti' :    ['Juan Schiaretti', 'Juan Schriareti', 'Schiareti', 'Squiareti',],
    'Horacio Rodriguez Larreta'  :    ['Horacio Rodriguez Larreta', 'Larreta', 'Lareta', 'Sombrilla', 'Pelado',],
    'Patricia Bullrich' :    ['Patricia Bullrich', 'Bullrich', 'Patricia Bulrich', 'Bulrich', 'Patricia', 'Pato', 'Montonera',],
    'Javier Milei' :    ['Javier Milei', 'Miley', 'Mi ley', 'Milaw', 'Leon', 'Peluca',],
    'Nazareno Etchepare' :    ['Nazareno Etchepare', 'Etchepare',],
    'Ramiro Vasena' :    ['Ramiro Vasena', 'Ramiro basena', 'Basena', 'Vasena',],
    'Manuela Casta√±eira' :    ['Manuela Casta√±eira', 'Casta√±eira', 'Manuela Castanieira', 'Castanieira',],
    'Raul Albarracin' :    ['Raul Albarracin', 'Albarracin', 'Albaracin',],
    'Raul Castells' :    ['Raul Castells', 'Raul Castels', 'Castells', 'Castels',],
    'Santiago Cuneo' :    ['Santiago Cuneo', 'Cuneo',],
    'Jesus Escobar' :    ['Jesus Escobar', 'Escobar',],
    'Marcelo Ramal' :    ['Marcelo Ramal', 'Ramal',],
    'Guillermo Moreno' :    ['Guillermo Moreno', 'Moreno',],
    'Oscar Giardinelli' :    ['Oscar Giardinelli', 'Oscar Giardineli', 'Giardinelli', 'Giardineli',],
    'Martin Ayerbe Ortiz'  :    ['Martin Ayerbe Ortiz', ],
    'Reina Iba√±ez' :    ['Reina Iba√±ez', 'Reina Xiomara Iba√±ez', ],
    'Andres Passamonti' :    ['Andres Passamonti', 'Passamonti', 'Pasamonti', ],
    'Sergio Tomas Massa'  :    ['Sergio Tomas Massa', 'Sergio Massa', 'Sergio Masa', 'Masa', 'Massa', 'Panqueque'],
    'Juan Grabois' :    ['Juan Grabois', 'Grabois', 'Gravois', ],
    'Julio Barbaro' :    ['Julio Barbaro', 'Barbaro', ],
    'Eliodoro Martinez' :    ['Eliodoro Martinez', ],
    'Jorge Oliver' :    ['Jorge Oliver', ],
    'Carolina Bartolini' :    ['Carolina Bartolini', 'Barotilin', ],
    'Paula Arias' :    ['Paula Arias'],
}
# lowercase and strip any extraspaces from all the candidates values
for candidate in candidates.keys():
    candidates[candidate] = [candidate.lower().strip() for candidate in candidates[candidate]]

# filter text based on the candidates present in the text. Add a new column 'candidate' to the df
def filter_text(text):
    text = unidecode(text)
    for candidate in candidates.keys():
        for candidate_name in candidates[candidate]:
            # deaccent spanish text
            if candidate_name in text:
                return True

    return False



# filter the text column
df = df[df['text'].progress_apply(filter_text)]

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 365210/365210 [09:07<00:00, 667.26it/s]

In [18]:
# add a new candidate column, add the name of candidates mentioned in the text
def add_candidate(text):
    candidates_list = set()
    for candidate in candidates.keys():
        for candidate_name in candidates[candidate]:
            if candidate_name in text:
                candidates_list.add(candidate)
    return candidates_list

df['candidate'] = df['text'].progress_apply(add_candidate)

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 92899/92899 [01:00<00:00, 1543.93it/s]

In [19]:
# for each candidate in the candidate column, add a new row with the same values except the candidate column
# Convert the candidate set to a string list
df['candidate_str'] = df['candidate'].apply(lambda x: list(x))
# explode the candidate column
df_exploded = df.explode('candidate_str')
df_exploded = df_exploded.reset_index(drop=True)
# drop the candidate column
df = df_exploded.drop(['candidate'], axis=1)
# rename the candidate_str column to candidate
df = df.rename(columns={'candidate_str': 'candidate'})
# make the candidate column to be the first column
df = df[['candidate', 'source', 'date', 'text']]

In [20]:
df

,candidate,source,date,text
0,Patricia Bullrich,rionegro,2023-08-15,el ciclo de r√≠o negro ¬´v√©rtices¬ª sigue hoy en ...
1,Javier Milei,rionegro,2023-08-15,el ciclo de r√≠o negro ¬´v√©rtices¬ª sigue hoy en ...
2,Sergio Tomas Massa,rionegro,2023-09-11,impuesto a las ganancias: massa anunciar√≠a sub...
3,NaN,rionegro,2023-09-28,a cosechar ahora flores de diente de le√≥n para...
4,Guillermo Moreno,rionegro,2022-06-14,¬øqu√© hacer en vacaciones de inverno en r√≠o neg...
...,...,...,...,...
151598,Horacio Rodriguez Larreta,youtube,2023-08-01,"agustina kampfer entrevist√≥ a c√©sar biondini, ..."
151599,Patricia Bullrich,youtube,2023-08-01,"agustina kampfer entrevist√≥ a c√©sar biondini, ..."
151600,Alejandro Biondini,youtube,2023-07-31,entrevista a c√©sar biondini en &quot;somos pm&...
151601,Patricia Bullrich,youtube,2023-07-31,entrevista a c√©sar biondini en &quot;somos pm&...
151602,Javier Milei,youtube,2023-07-31,entrevista a c√©sar biondini en &quot;somos pm&...

In [25]:
df.query('candidate=="Horacio Rodriguez Larreta" & source=="clarin"')

,candidate,source,date,text
11511,Horacio Rodriguez Larreta,clarin,2023-06-12,el gobernador electo de san luis toma partido ...
11702,Horacio Rodriguez Larreta,clarin,2023-06-12,el dato que inquieta a massa: una devaluaci√≥n ...
13678,Horacio Rodriguez Larreta,clarin,2023-06-12,"qui√©n es claudio poggi, el ex delf√≠n de los ro..."
14087,Horacio Rodriguez Larreta,clarin,2023-06-12,"tras la victoria en san luis, larreta, carri√≥,..."

In [17]:
# how many entries does each cand website have?
df['source'].value_counts()

source
youtube         74528
perfil          17363
eldestapeweb    12302
rionegro        10681
c5n             10522
lanacion         6365
clarin           4904
lavoz            4410
pagina12         2824
infobae          1643
Name: count, dtype: int64

In [18]:
# save it as a csv
df.to_csv('preprocessed_data.csv', index=False)